In [53]:
%load_ext cudf.pandas
import pandas as pd

The cudf.pandas extension is already loaded. To reload it, use:
  %reload_ext cudf.pandas

In [54]:
file_path = "/home/nishad/Bariatric/Data/Databricks/clinical_notes_b_encs.csv.gz"

In [55]:
df_databricks = pd.read_csv(file_path)

In [56]:
df_databricks.head()

,MRN,patient_id,encounter_id,note_text
0,20813922,23725183,47887951,\n\n\n\n\n\n\n\t\n\t\t\n\t\t\n\t\n\t\n\t\t\n\t...
1,20648834,10355838,48583759,"Children's National Hospital - DC, Maryland, V..."
2,21525533,69131623,48599949,ED Disposition Documentation Entered On: 05/2...
3,21154603,52749504,48293249,"Patient: COLE, JAELYN PATRICIA MR..."
4,20543391,5101376,48425455,SZ ED Triage/Assessment Entered On: 05/07/202...

In [57]:
df_databricks['MRN'].nunique()

754

In [58]:
test1 = df_databricks[df_databricks['MRN'] == 20564447]

In [59]:
test1.sort_values(by='encounter_id')

,MRN,patient_id,encounter_id,note_text
55879,20564447,3738502,24551376,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
26593,20564447,3738502,33745052,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
77997,20564447,3738502,35095803,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
37320,20564447,3738502,35761852,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
32784,20564447,3738502,39851007,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
...,...,...,...,...
21416,20564447,3738502,61843588,"---------------------\nFrom: BANACH, LAURIE PA..."
18674,20564447,3738502,61843588,"---------------------\nFrom: Uy, Liane Mai (CN..."
94783,20564447,3738502,61843588,"---------------------\nFrom: Uy, Liane Mai (CN..."
9358,20564447,3738502,63395800,** Approved **\nOrder:ethinyl estradiol-norges...
84505,20564447,3738502,63395800,"---------------------\nFrom: Uy, Liane Mai (CN..."

In [60]:
enc_list = list(set(test1['encounter_id'].to_list()))

In [61]:
enc_list[-5]

41766641

In [63]:
df_filtered_0 = test1[test1['note_text'].str.contains('note', na=False)]
df_filtered_1 = test1[test1['note_text'].str.contains('Note', na=False)]
df_filtered_2 = test1[test1['note_text'].str.contains('report', na=False)]
df_filtered_3 = test1[test1['note_text'].str.contains('Report', na=False)]

In [64]:
df_filtered_0

,MRN,patient_id,encounter_id,note_text
8223,20564447,3738502,45602957,\n\n\n\n\n\n\nThis visit was conducted via tel...
9514,20564447,3738502,61437352,"---------------------\nFrom: Uy, Liane Mai (CN..."
16463,20564447,3738502,48301165,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
16534,20564447,3738502,49901264,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
18674,20564447,3738502,61843588,"---------------------\nFrom: Uy, Liane Mai (CN..."
19401,20564447,3738502,45696451,"Patient: MABRY, CIARA LACHELLE MR..."
21797,20564447,3738502,61396904,\n\n\n\n\n\n\n\t\n\t\t\n\t\t\n\t\n\t\n\t\t\n\t...
22024,20564447,3738502,60420121,"---------------------\nFrom: Uy, Liane Mai (CN..."
26593,20564447,3738502,33745052,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
29616,20564447,3738502,46770399,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
30372,20564447,3738502,49204847,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
30422,20564447,3738502,48303113,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
32079,20564447,3738502,57401126,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
32784,20564447,3738502,39851007,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
32971,20564447,3738502,42936327,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
33002,20564447,3738502,41266258,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
33169,20564447,3738502,40681791,\n\n\n\n\n\nChief Complaint\n\nG4733\n\n\nHist...
37320,20564447,3738502,35761852,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
38517,20564447,3738502,57401126,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
41250,20564447,3738502,41419355,\n\n\n\n\n\nPatient Summary\n\n\n\n\nChief Com...
44839,20564447,3738502,57401126,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
54880,20564447,3738502,47270402,\n\n\n\n\n\n\nI had the opportunity to see Cia...
55879,20564447,3738502,24551376,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
71693,20564447,3738502,47440299,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
77997,20564447,3738502,35095803,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
83318,20564447,3738502,44193887,"<HTML>\r\n <HEAD>\r\n <META http-equiv=""Co..."
85141,20564447,3738502,54205427,\n\n\n\n\n\n\n\t\n\t\t\n\t\t\n\t\n\t\n\t\t\n\t...
92246,20564447,3738502,59832003,"---------------------\nFrom: Uy, Liane Mai (CN..."

In [65]:
note = test1[test1['encounter_id'] == 45696451]

In [66]:
note

,MRN,patient_id,encounter_id,note_text
16787,20564447,3738502,45696451,"\n\n\n\n\n\n\n\n\n\n\t\n\t\t\n\t\t\tMABRY, CIA..."
18887,20564447,3738502,45696451,This document is a working copy of Patient Edu...
19397,20564447,3738502,45696451,CNMC PACU Nursing Record Summary ...
19401,20564447,3738502,45696451,"Patient: MABRY, CIARA LACHELLE MR..."
20315,20564447,3738502,45696451,Signing Pathologist:\n Christopher T. Rossi...
23418,20564447,3738502,45696451,"PT role, PT POC"
24134,20564447,3738502,45696451,II*
25706,20564447,3738502,45696451,"Stomach, laparoscopic sleeve gastrectomy:\n- N..."
28915,20564447,3738502,45696451,Stomach
28969,20564447,3738502,45696451,Gross Pathologist(s):\nEmily J. Loter
28987,20564447,3738502,45696451,Billing Fee codes(s):\n1570-70190H (88307T) x ...
29072,20564447,3738502,45696451,The patient is a 15-year-old male with a histo...
29114,20564447,3738502,45696451,ICD 9(s):\nE66.01
29119,20564447,3738502,45696451,Ordering Physician:\n EVAN PAUL NADLER
29282,20564447,3738502,45696451,Old Billing Number:\n 2010801402\020564447\...
29290,20564447,3738502,45696451,The specimen is received in a formalin-filled ...
29295,20564447,3738502,45696451,Patient Location:\n PVU
80895,20564447,3738502,45696451,"\n\n\n\n\n\nChief Complaint \n\n\n\nObesity, B..."
80960,20564447,3738502,45696451,NaN
80981,20564447,3738502,45696451,Ciara is a 15 yr old girl with a history of ob...
80996,20564447,3738502,45696451,"Patient: MABRY, CIARA LACHELLE MR..."
81022,20564447,3738502,45696451,Pharmacy Clinical Interventions Entered On: 0...
81041,20564447,3738502,45696451,"PIV, pulse ox, CR leads"
81056,20564447,3738502,45696451,Click the hyperlink below to view the report
81080,20564447,3738502,45696451,CNMC PreOp Nursing Record Summary ...
98756,20564447,3738502,45696451,*Converted case* This report may not match the...
98843,20564447,3738502,45696451,Specimen Client:\n CHW
98887,20564447,3738502,45696451,Old Case Number:\n S20-3031
102501,20564447,3738502,45696451,\n\n\n\n\n\n\n\t\n\t\t\n\t\t\n\t\t\n\t\n\t\n\t...
105204,20564447,3738502,45696451,"Patient: MABRY, CIARA LACHELLE MR..."
106779,20564447,3738502,45696451,Patient MRN Client:\n CHW
106932,20564447,3738502,45696451,Ciara is a 15 yr old girl with a history of ob...
106959,20564447,3738502,45696451,"Patient: MABRY, CIARA LACHELLE MR..."
109846,20564447,3738502,45696451,\n\n\n\n\n\n\nDATE OF SURGERY: 06/08/2020\nSUR...

In [68]:
print(note.loc[106959]['note_text'])

Patient:   MABRY, CIARA LACHELLE            MRN: 020564447            FIN: 2010801402
Age:   15 years     Sex:  Female     DOB:  02/13/05
Associated Diagnoses:   None
Author:   VAUGHNS, JANELLE DENISE MD

Postoperative Information
VS/Measurements
VS/Measurements Ranges
Vital Ranges
Between 06/08/20 07:00  AND: 06/09/20 06:59
This View Created @: 06/09/20 06:28

Vital Signs		Min	Max
Temperature Oral                  36.6     36.6  DegC  (3)
Heart Rate Monitored            77        95  bpm  (14)
Respiratory Rate                     12        29  br/min  (14)
Systolic Blood Pressure          119        158  mmHg  (13)
Diastolic Blood Pressure         73        90  mmHg  (13)
Mean Arterial Pressure          90        107  mmHg  (12)
 BP Methods:                           Cuff - Automated
 BP Locations:                          Arm, L,Arm, R
SpO2                                        99           100  %  (14)
SpO2 Site:                                Hand, Left,Hand, Right.  Measurements from flow sheet : Measurements
06/08/20 18:36 EDT|Height|169.5 cm|
|Measured Weight|136.3 kg  Normal|
|Body Mass Index Measured|47.44 kg/m2|
06/08/20 10:43 EDT|Height|169.5 cm|
|Med Calc Weight|136.3 kg  Normal|



Recovery Score: 10

Medication History: Sched: pantoprazole inj in NS, ketorolac 30 mg/mL INJ Soln 1 mL, acetaminophen inj, Dextrose 5% with 0.45% NaCl and KCl 20 mEq/L intravenous solution 1000 mL, Dextrose 5% with 0.45% NaCl and KCl 20 mEq/L 1,000 mL, lisdexamfetamine PRN: morphine sulfate PF 2 mg/mL INJ Soln 1 mL, lidocaine 4% (LMX) Top Cre 5 gm, ondansetron 2 mg/mL INJ Soln 2 mL

Physical Examination
HEENT:  Normal.
Dentition:  Normal.
Lungs:  Clear.
Heart:  Regular, rate and rhythm.
Neurobehavioral:  Calm.

Assessment
Vital signs:  Heart rate, respiratory rate, blood pressure, temperature, andl oxygen saturation are all within normal limits and stable.
Airway:  Patent.
Respiratory:  Spontaneous respirations, On room air.
Cardiovascular:  Stable.
Pain management:  Adequate.
Post operative nausea/vomiting management:  Adequate.
Hydration management:  Adequate.
Mental status:  The patient has adequately recovered from general anesthesia..

Impression and Plan
Overall Status:  Progressing as expected.
Plan of Care:  Admitted to acute care unit.

In [ ]:
test1['encounter_id'].dtype